language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pylint flake8 -r requirements.txt
# command to run tests
script:
  - pylint scripts/*.py
  - flake8 --ignore=E501 scripts/*.py
  - cd scripts && shellcheck desk_* exit_menu *.sh