language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pylint flake8 black -r requirements.txt
# command to run tests
script:
  - black --check $(find . -name "*.py")
  - pylint $(find . -name "*.py")
  - flake8 --ignore=E501 $(find . -name "*.py")
  - shellcheck $(find . -name "*.sh")