language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -U pip -r requirements.txt
before_script:
  - export BASH_FILES=$(find . -name "*.sh")
  - export PYTHON_FILES=$(find . -name "*.py")
# command to run tests
script:
  - black --config i3.toml .
  - pylint $PYTHON_FILES
  - flake8 --ignore=E501 .
  - shellcheck $BASH_FILES
